# Generated by Django 4.0.2 on 2022-02-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
